docs: minor update to readme.md
openebs/mayastor-docs pull request #59
Opened 2022-09-13 10:08 UTC by anupriya0703

This change adds info about 'openebs/mayastor-extensions' repo.

Signed-off-by: anupriya0703 <anupriya.gupta@mayadata.io>

2022-09-16 11:09 UTC, avishnu commented on README.md
> +- [openebs/mayastor-extensions](https://github.com/openebs/mayastor-extensions) : contains components and utilities that extend core Mayastor's functionalities.
"that provide extended functionalities like ease of installation, monitoring and observability aspects."

How about the above?

2022-09-26 15:33 UTC, avishnu approved these changes
lgtm

2022-09-26 16:48 UTC, GlennBullingham approved these changes
Approved

2022-09-26 16:50 UTC, GlennBullingham requested changes
Actually, taking that approval back ;-)

Line 31 is the only line with a full-stop at the end.  Remove it for consistency?

2022-10-02 19:23 UTC, GlennBullingham approved these changes
LGTM

2022-10-04 06:25 UTC, merged